Backend/Controllers/AnalyzerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WechatBackend.Controllers
{
    public class AnalyzerController : Controller
    {
        // GET: Analyzer
        public ActionResult Index()
        {
            return View();
        }
    }
}

Backend/Views/Analyzer/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>微信分享管理平台v1.0</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <style>
        span.field-validation-error {
            color: red;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("微信分享管理平台 v1.0", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("分享管理", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("分享统计", "Index", "Analyzer", new { area = "" }, null)</li>
                    <!--
                        <li>@Html.ActionLink("API", "Index", "Help", new { area = "HelpPage" }, null)</li>
                    -->
                </ul>

            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>

        </div>
    </div>

    <script src="~/Scripts/highcharts.js"></script>
    <script src="~/Scripts/modules/exporting.js"></script>


    <div id="piecontainer" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
    <div id="linecontainer"></div>

    <script type="text/javascript">


        $.ajax({
            async: false, //使用同步的Ajax请求
            type: "post",
            url: "/services/Urlpie.ashx",
            success: function (msg) {
                drawpie(msg);
            }
        });

     


        function drawpie(piedata) {
            Highcharts.chart('piecontainer', {
                chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    type: 'pie'
                },
                title: {
                    text: '各URL分享次数统计'
                },
                tooltip: {
                    pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                            style: {
                                color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                            }
                        },
                        point: {
                            events: {
                                click: function (event) {
                                    //alert(this.name);
                                    name = this.name;
                                    $.ajax({
                                        async: false, //使用同步的Ajax请求
                                        type: "post",
                                        url: "/services/LineChat.ashx",
                                        data: { "url": name},
                                        dataType: "json",
                                        success: function (msg) {
                                            drawline(msg, name);
                                        }
                                    });
                                }
                            }
                        } 
                    }
                },
                series: [{
                    name: '占总比率',
                    colorByPoint: true,
                    data: piedata
                }]
            });
        }


        function drawline(linedata,name) {

            var x = linedata[0].categories
            var xArray = new Array()
            for (i = 0; i < x.split(',').length; i++) {
                xArray[i] = x.split(',')[i];
            }
            var y = linedata[0].data
            var yArray = new Array()
            for (j = 0; j < y.split(',').length; j++) {
                yArray[j] = parseInt(y.split(',')[j]);
            }
            x = xArray
            y = yArray

            Highcharts.chart('linecontainer', {
                title: {
                    text: '('+name+')微信分享分析'
                },
                subtitle: {
                    text: '24小时分享情况曲线'
                },
                chart: {
                    type: 'line'
                },
                xAxis: {
                    categories: x
                },
                series: [{
                    name: name,
                    data: y
                        }
                     ]
            });
        }

    </script>



</body>
</html>